application: it-katas
version: 2-3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: yaml
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: numpy
  version: latest
