application: it-katas
version: 2-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: yaml
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: numpy
  version: latest
